import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Curado a mano en vez de autogenerated: el frente del sitio se mantiene
// chico a propósito (Intro, Guía rápida, Herramientas básicas, Arquitectura).
// Todo lo demás sigue existiendo tal cual, sin mover ni un archivo — solo
// baja de prioridad visual dentro de "Avanzado", colapsado por defecto.
// Se "acopla" contenido nuevo a Arquitectura a medida que se construye de
// verdad, en vez de mantener 20 categorías abiertas desde el día uno.
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'guia-rapida',
    'primeros-pasos/herramientas-basicas',
    {
      type: 'category',
      label: 'Arquitectura',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'arquitectura/vision-general',
      },
      items: [
        'arquitectura/vision-general',
        'arquitectura/principios',
        'arquitectura/stack',
        'arquitectura/topologia-logica',
        'arquitectura/estado-actual',
        'referencia/requisitos-minimos',
      ],
    },
    {
      type: 'category',
      label: 'Avanzado — profundizar',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Avanzado',
        description:
          'Todo lo que no hace falta leer el primer día: instalación por servicio, ADRs, runbooks, labs, seguridad, backups y más. Nada de esto se borró — se despriorizó para que el frente del sitio no abrume.',
      },
      items: [
        'arquitectura/decisiones-arquitectonicas',
        {type: 'autogenerated', dirName: 'hardware'},
        {type: 'autogenerated', dirName: 'red'},
        {type: 'autogenerated', dirName: 'proxmox'},
        {type: 'autogenerated', dirName: 'servicios'},
        {type: 'autogenerated', dirName: 'devops'},
        {type: 'autogenerated', dirName: 'kubernetes'},
        {type: 'autogenerated', dirName: 'observabilidad'},
        {type: 'autogenerated', dirName: 'automatizacion'},
        {type: 'autogenerated', dirName: 'hogar'},
        {type: 'autogenerated', dirName: 'juegos'},
        {type: 'autogenerated', dirName: 'ia'},
        {type: 'autogenerated', dirName: 'seguridad'},
        {type: 'autogenerated', dirName: 'backup-dr'},
        {type: 'autogenerated', dirName: 'despliegues'},
        {type: 'autogenerated', dirName: 'laboratorios'},
        {type: 'autogenerated', dirName: 'runbooks'},
        {type: 'autogenerated', dirName: 'troubleshooting'},
        {type: 'autogenerated', dirName: 'roadmap'},
        'referencia/comandos',
        'referencia/deploy-railway',
        'referencia/glosario',
        'referencia/mantener-docusaurus',
        'referencia/naming',
        'referencia/puertos',
      ],
    },
  ],
};

export default sidebars;
